I give up I will fix this one day in the future!

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -15,64 +15,35 @@ on:
     branches: [ "master" ]
 
 jobs:
-  common-setup:
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout repository
-        uses: actions/checkout@v3
-
-      - name: Install Java 17
-        run: |
-          sudo apt-get update
-          sudo apt-get install -y openjdk-17-jdk
-          echo "Java 17 installed successfully"
-
-      - name: Set JAVA_HOME and PATH
-        run: |
-          echo "export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64" >> $GITHUB_ENV
-          echo "export PATH=${JAVA_HOME}/bin:${PATH}" >> $GITHUB_ENV
-          echo "Java 17 set as default"
-
-      - name: Set up Chrome
-        uses: browser-actions/setup-chrome@latest
-
-      - name: Print current directory
-        run: pwd
-
-      - name: List files in the current directory
-        run: ls -l
-
   build:
-    needs: common-setup
+
     runs-on: ubuntu-latest
+
     steps:
-      - name: Checkout repository
-        uses: actions/checkout@v3
+    - uses: actions/checkout@v3
+    - name: Set up JDK 17
+      uses: actions/setup-java@v3
+      with:
+        java-version: '17'
+        distribution: 'temurin'
+        cache: maven
+    - uses: browser-actions/setup-chrome@latest
+    - run: chrome --version
 
-      - name: Change to repository root directory
-        run: cd $GITHUB_WORKSPACE
+    - name: Build with Maven
+      run: mvn --batch-mode -DskipTests package
+    - name: Test
+      run: mvn --batch-mode test -Dmaven.test.failure.ignore=true -Dproperty=RunRemote.properties -DgroupToRun=all -Dthreads=4 -DreportName=report
 
-      - name: List files in the current directory
-        run: ls -l
-
-      - name: Print current directory
-        run: pwd
-
-      - name: Print Java version
-        run: java -version
-
-      - name: Set Java 17 for Maven
-        run: |
-          ./mvnw -N io.takari:maven:wrapper -Dmaven=3.8.8
-          chmod +x mvnw
-
-      - name: Verify Maven wrapper
-        run: ./mvnw --version
-
-      - name: Build with Maven
-        run: ./mvnw --batch-mode -DskipTests package -Dmaven.compiler.release=17
-
-
+      #Test report generation 
+    - name: Test Report
+      uses: dorny/test-reporter@v1.9.0       # repo used to build report!
+      if: success() || failure()             # run this step even if previous step failed
+      with:
+        name: Automation Test                # Name of the check run which will be created
+        path: target/surefire-reports/*.xml  # Path to test results
+        reporter: java-junit                 # Format of test results
+        fail-on-error: true
 
 
         
