final changes for yml file to show report after PR

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -34,19 +34,15 @@ jobs:
       run: mvn --batch-mode -DskipTests package
     - name: Test
       run: mvn --batch-mode test -Dmaven.test.failure.ignore=true -Dproperty=RunRemote.properties -DgroupToRun=all -Dthreads=4 -DreportName=report
-    - name: Publish Test Report
-      if: success() || failure()
-      uses: ScaCap/action-surefire-report@v1.8.0
-      with: 
-        github_token: ${{ secrets.GITHUB_TOKEN }}
-        report_paths: "**/target/surefire-reports/TEST-*.xml"
-    - name: Report
-      uses: dorny/test-reporter@v1.9.0
-      if: success() || failure()    # run this step even if previous step failed
+
+      #Test report generation 
+    - name: Test Report
+      uses: dorny/test-reporter@v1.9.0       # repo used to build report!
+      if: success() || failure()             # run this step even if previous step failed
       with:
-        name: Automation Test            # Name of the check run which will be created
-        path: target/surefire-reports/*.xml    # Path to test results
-        reporter: java-junit        # Format of test results
+        name: Automation Test                # Name of the check run which will be created
+        path: target/surefire-reports/*.xml  # Path to test results
+        reporter: java-junit                 # Format of test results
         fail-on-error: true
         
     # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
